## index

1. input&output file in R
2.

# 1. input&output file in R


- 엑셀파일에 테이블형태 데이터가 저장되어있는 경우 가정
- 엑셀파일을 .csv로 변환하여 저장 후, r에서 .csv파일 읽음
- 읽어온 파일은 데이터프레임 형태로 저장됨

데이터 읽기

In [ ]:
# 로컬의경우
# setwd("D:/source") # 작업폴더 지정

air <- read.csv("airquality.csv", header=T)
head(air)

  Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1
2 36    118      8.0 72   5     2
3 12    149     12.6 74   5     3
4 18    313     11.5 62   5     4
5 NA     NA     14.3 56   5     5
6 28     NA     14.9 66   5     6

데이터 쓰기

In [ ]:
# 로컬의경우
# setwd("D:/source") # 작업폴더 지정

my.iris <- subset(iris, Species='Setosa')      # Setosa 품종 데이터만 추출
write.csv(my.iris, "my_iris.csv", row.names=F) #.csv 파일에 저장하기